### ISSUE TITLE
갑자기 카메라가 회전하는 현상에 관해서.

### ISSUE THREAD

**Issue by Kumazuma** [MisterPark/LOL-Portfolio#13]
![image](https://user-images.githubusercontent.com/12020335/108390121-ade12e80-7253-11eb-9fa8-6529d113600a.png)

줌인/줌아웃을 하는 경우 카메라의 회전이 이상해 지는 문제점이 있음.

**Comment by MisterPark** [comment]
확인후 수정할게요

**Comment by MisterPark** [comment]
수정함
